// ZOS Build Macros - Minimal working foundation
// AGPL-3.0 License

use proc_macro::TokenStream;

// Disabled modules with broken code
#[cfg(feature = "broken")]
pub mod broken;

#[cfg(feature = "experimental")]
pub mod future;

/// Minimal build macro - just generates basic build.rs
#[proc_macro]
pub fn mkbuild(_input: TokenStream) -> TokenStream {
    let build_code = r#"
// Generated by mkbuild! macro - Minimal foundation
use std::env;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let features = env::var("CARGO_CFG_FEATURE").unwrap_or_default();

    // Layer 0: Foundation
    if features.contains("foundation") {
        println!("cargo:rustc-cfg=layer_0");
    }

    // LMFDB integration
    if features.contains("lmfdb") {
        println!("cargo:rustc-cfg=lmfdb_enabled");
    }
}
"#;

    build_code.parse().unwrap()
}

/// Placeholder for future context expansion
#[proc_macro]
pub fn mkscript(_input: TokenStream) -> TokenStream {
    "// Script generation placeholder".parse().unwrap()
}

/// Placeholder for future layer configuration
#[proc_macro]
pub fn mklayer(_input: TokenStream) -> TokenStream {
    "// Layer configuration placeholder".parse().unwrap()
}
