#!/bin/bash

echo "💰 ZOS Referral Commission System Demo"
echo "====================================="

echo ""
echo "🔗 Creating Referral Links:"
echo ""

echo "1. Alice creates referral link for her AI service:"
echo "   POST /create-referral"
echo "   {"
echo "     \"referrer_wallet\": \"alice123...\","
echo "     \"service_endpoint\": \"alice123.../gpt-service\","
echo "     \"custom_params\": {\"promo\": \"AI50\"}"
echo "   }"
echo ""
echo "   Response: https://node1.solfunmeme.com/alice123.../gpt-service?ref=ref_alice123_1736445892"

echo ""
echo "2. Bob clicks Alice's referral link and makes first transaction:"
echo "   GET /alice123.../gpt-service?ref=ref_alice123_1736445892"
echo "   → Tracks Bob as Alice's referral"
echo "   → Alice earns 10% of Bob's future fees"

echo ""
echo "💸 Commission Structure:"
echo ""
echo "Swap Commissions (20% of swap fees):"
echo "  • User swaps 100 SOLFUNMEME → 95 USDC"
echo "  • Swap fee: 2 USDC"
echo "  • Service owner earns: 0.4 USDC (20% of 2 USDC)"

echo ""
echo "Referral Commissions (10% of referee's fees):"
echo "  • Bob (referred by Alice) pays 1 USDC service fee"
echo "  • Alice earns: 0.1 USDC (10% of 1 USDC)"
echo "  • With Gold tier (1.5x): Alice earns 0.15 USDC"

echo ""
echo "Service Commissions (5% of service payments):"
echo "  • User pays 10 USDC for AI service"
echo "  • Service owner earns: 0.5 USDC (5% of 10 USDC)"

echo ""
echo "🏆 Earnings Tiers & Multipliers:"
echo ""
echo "Bronze (0-10 referrals):    1.0x multiplier"
echo "Silver (11-50 referrals):   1.2x multiplier"
echo "Gold (51-200 referrals):    1.5x multiplier"
echo "Platinum (201+ referrals):  2.0x multiplier"

echo ""
echo "📊 Example Earnings Dashboard:"
echo ""
echo "{"
echo "  \"wallet_address\": \"alice123...\","
echo "  \"earnings\": {"
echo "    \"total_earned_usdc\": 1247.50,"
echo "    \"lifetime_volume\": 12475.00,"
echo "    \"pending_withdrawals\": 0.0"
echo "  },"
echo "  \"referrals\": {"
echo "    \"total_referrals\": 73,"
echo "    \"current_tier\": \"Gold\","
echo "    \"tier_multiplier\": 1.5"
echo "  },"
echo "  \"referral_links\": ["
echo "    {"
echo "      \"service_endpoint\": \"alice123.../gpt-service\","
echo "      \"clicks\": 1247,"
echo "      \"conversions\": 73,"
echo "      \"conversion_rate\": 5.85"
echo "    }"
echo "  ],"
echo "  \"commission_rates\": {"
echo "    \"swap_commission\": 20.0,"
echo "    \"referral_commission\": 10.0,"
echo "    \"service_commission\": 5.0"
echo "  }"
echo "}"

echo ""
echo "🎯 Revenue Streams for Wallet Holders:"
echo ""
echo "1. 📱 Service Hosting: Earn from your own services"
echo "2. 🔄 Swap Commissions: 20% of swap fees on your endpoint"
echo "3. 👥 Referral Bonuses: 10% of referred users' fees (with tier multipliers)"
echo "4. 💼 Service Fees: 5% of payments to services you host"
echo "5. 📈 Volume Bonuses: Higher tiers = higher multipliers"

echo ""
echo "💡 Growth Strategy:"
echo ""
echo "• Share referral links on social media"
echo "• Create valuable services to attract users"
echo "• Build community around your services"
echo "• Reach higher tiers for better multipliers"
echo "• Compound earnings by reinvesting in better services"

echo ""
echo "🚀 API Endpoints:"
echo ""
echo "POST /create-referral          → Create referral link"
echo "GET  /earnings/{wallet}        → View earnings dashboard"
echo "GET  /referrals/{wallet}       → List referral performance"
echo "POST /withdraw-earnings        → Withdraw accumulated earnings"
echo "GET  /commission-history       → View commission payment history"
