#!/bin/bash

# ZOS AI Marketplace Demo
echo "🤖 ZOS AI Marketplace Demo"
echo "=========================="

echo ""
echo "📝 Publishing AI Prompts:"
echo ""

# Code generation prompt
echo "1. 🔧 Code Generator Prompt"
echo "   Title: 'Rust Function Generator'"
echo "   Template: 'Generate a Rust function that {input}. Include error handling and documentation.'"
echo "   Price: 5 credits per request"
echo "   Category: CodeGeneration"

# Content writing prompt
echo ""
echo "2. ✍️  Content Writer Prompt"
echo "   Title: 'Blog Post Creator'"
echo "   Template: 'Write a professional blog post about {input}. Include introduction, main points, and conclusion.'"
echo "   Price: 3 credits per request"
echo "   Category: ContentWriting"

# Data analysis prompt
echo ""
echo "3. 📊 Data Analyzer Prompt"
echo "   Title: 'CSV Data Insights'"
echo "   Template: 'Analyze this data: {input}. Provide key insights, trends, and recommendations.'"
echo "   Price: 8 credits per request"
echo "   Category: DataAnalysis"

echo ""
echo "🖥️  Available LLM Endpoints:"
echo ""

echo "1. 🧠 GPT-4 Endpoint (Port 20001)"
echo "   Owner: alice_123"
echo "   Model: gpt-4-turbo"
echo "   Max Tokens: 8192"
echo "   Cost: 0.001 credits/token"
echo "   Uptime: 99.5%"

echo ""
echo "2. 🤖 Claude Endpoint (Port 20002)"
echo "   Owner: bob_456"
echo "   Model: claude-3-sonnet"
echo "   Max Tokens: 4096"
echo "   Cost: 0.0008 credits/token"
echo "   Uptime: 98.2%"

echo ""
echo "3. 💻 Code Llama Endpoint (Port 20003)"
echo "   Owner: charlie_789"
echo "   Model: codellama-34b"
echo "   Max Tokens: 2048"
echo "   Cost: 0.0005 credits/token"
echo "   Uptime: 97.8%"

echo ""
echo "💳 User Quotas by Tier:"
echo ""
echo "Free:     10 requests/day,   10K tokens/month,   100 credits"
echo "Bronze:   50 requests/day,   50K tokens/month,   500 credits"
echo "Silver:  200 requests/day,  200K tokens/month,  2000 credits"
echo "Gold:   1000 requests/day,    1M tokens/month, 10000 credits"
echo "Platinum: Unlimited requests, Unlimited tokens, Unlimited credits"

echo ""
echo "🎯 Example Usage:"
echo ""

echo "# Execute a published prompt"
echo "curl -X POST localhost:3000/ai/execute-prompt \\"
echo "  -d '{\"prompt_id\":\"prompt_rust_gen\", \"input\":\"sorts an array of integers\"}'"
echo ""
echo "Response:"
echo "{"
echo "  \"result\": \"fn sort_integers(arr: &mut [i32]) -> Result<(), String> {\""
echo "  \"tokens_used\": 156,"
echo "  \"cost_credits\": 5,"
echo "  \"processing_time_ms\": 1500"
echo "}"

echo ""
echo "# Direct LLM request"
echo "curl -X POST localhost:3000/ai/direct-request \\"
echo "  -d '{\"endpoint_id\":\"endpoint_alice_20001\", \"prompt\":\"Explain quantum computing\"}'"
echo ""
echo "Response:"
echo "{"
echo "  \"result\": \"Quantum computing harnesses quantum mechanics...\","
echo "  \"tokens_used\": 234,"
echo "  \"cost_credits\": 12,"
echo "  \"processing_time_ms\": 2000"
echo "}"

echo ""
echo "💰 Revenue Sharing Model:"
echo ""
echo "Prompt Creator:     70% of request fee"
echo "Platform Fee:       20% of request fee"
echo "Endpoint Provider:  10% of request fee"
echo ""
echo "Example: 10 credit request = 7 to creator + 2 platform + 1 endpoint"

echo ""
echo "📈 Marketplace Features:"
echo ""
echo "✨ Browse prompts by category"
echo "⭐ Rate and review prompts"
echo "📊 Usage analytics and earnings"
echo "🔄 Revenue sharing automation"
echo "🎯 Smart endpoint routing"
echo "📱 Real-time quota monitoring"

echo ""
echo "🚀 Try the AI Marketplace:"
echo "  Web UI: http://localhost:3000/ai-marketplace"
echo "  API:    http://localhost:3000/api/ai/"
echo "  Docs:   http://localhost:3000/ai-docs"
