#!/bin/bash
# Build Replication Script
# Generated by ZOS Build Audit System

set -euo pipefail

echo "🔄 Replicating ZOS build..."

# Check environment
if ! command -v rustc &> /dev/null; then
    echo "❌ Rust not found. Install Rust first."
    exit 1
fi

if ! command -v cargo &> /dev/null; then
    echo "❌ Cargo not found. Install Cargo first."
    exit 1
fi

# Verify Rust version
REQUIRED_RUST="1.70.0"
CURRENT_RUST=$(rustc --version | cut -d' ' -f2)
echo "📋 Rust version: ${CURRENT_RUST} (required: ${REQUIRED_RUST}+)"

# Clone or update repository
if [ ! -d "zos-server" ]; then
    echo "📥 Cloning ZOS repository..."
    git clone <repository_url> zos-server
fi

cd zos-server

# Checkout specific commit if provided
if [ "${1:-}" != "" ]; then
    echo "🔄 Checking out commit: $1"
    git checkout "$1"
fi

# Run build audit
if [ -f "build_audit.sh" ]; then
    echo "🔍 Running build audit..."
    ./build_audit.sh
else
    echo "⚠️  No build audit script found, running basic build..."
    cargo build --release
fi

echo "✅ Build replication complete!"
