pub mod libp2p_plugin;
pub mod libp2p_c_interface;
pub mod systemd_plugin;
pub mod oracle_plugin;
pub mod docker_plugin;
pub mod kernel_plugin;
pub mod ebpf_plugin;
pub mod solana_plugin;
pub mod wasm_plugin;
pub mod runtime_plugins;
pub mod storage_plugins;
pub mod blockchain_plugins;
pub mod telemetry_plugin;
pub mod compiler_plugins;
pub mod bintools_plugins;
pub mod debug_plugins;
pub mod dataformat_plugins;
pub mod protocol_plugins;
pub mod foundation_plugins;
pub mod governance_plugins;
pub mod regulatory_plugins;
pub mod zk_plugins;
pub mod advanced_zk_plugins;
pub mod enterprise_plugins;
pub mod security_plugins;
pub mod dataflow_plugins;
pub mod knowledge_plugins;
pub mod modeling_plugins;

pub use libp2p_plugin::LibP2PPlugin;
pub use systemd_plugin::SystemDPlugin;
pub use oracle_plugin::OraclePlugin;
pub use docker_plugin::DockerPlugin;
pub use kernel_plugin::KernelPlugin;
pub use ebpf_plugin::EbpfPlugin;
pub use solana_plugin::SolanaPlugin;
pub use wasm_plugin::WasmPlugin;
pub use runtime_plugins::{NodeJsPlugin, PythonPlugin, NixPlugin};
pub use storage_plugins::{IpfsPlugin, S3Plugin, SftpPlugin};
pub use blockchain_plugins::{EthereumPlugin, BitcoinPlugin};
pub use telemetry_plugin::TelemetryPlugin;
pub use compiler_plugins::{RustcPlugin, GccPlugin, LlvmPlugin};
pub use bintools_plugins::{ObjdumpPlugin, BinutilsPlugin, LinkerPlugin};
pub use debug_plugins::{GdbPlugin, StracePlugin, PtracePlugin, ChrootPlugin};
pub use dataformat_plugins::{ParquetPlugin, HuggingFacePlugin, RdfPlugin, SqlPlugin};
pub use protocol_plugins::{McpPlugin, OpenApiPlugin, SoapPlugin};
pub use foundation_plugins::{LmfdbPlugin, WikidataPlugin, OsmPlugin, ArchivePlugin, SdfPlugin};
pub use governance_plugins::{VotingPlugin, ResourcePlugin, OdooPlugin};
pub use regulatory_plugins::{SecPlugin, QualityPlugin, RegulatoryPlugin};
pub use zk_plugins::{ZkSnarkPlugin, ZkStarkPlugin, CorrectnessPlugin};
pub use advanced_zk_plugins::{RollupPlugin, LatticeFoldingPlugin, HmePlugin, MetaCoqPlugin, Lean4Plugin, SelfCarryingProofPlugin};
pub use enterprise_plugins::{ItilPlugin, C4Plugin, PlantUmlPlugin, JiraPlugin, GithubPlugin, CommunicationPlugin, DioxusPlugin, PhantomWalletPlugin, TerminalPlugin};
pub use security_plugins::{WireGuardPlugin, AsciinemaPlugin, TorPlugin, BluetoothMeshPlugin, SopsPlugin, GpgPlugin};
pub use dataflow_plugins::{PipesPlugin, QueuesPlugin, FanoutPlugin, StreamsPlugin, WorkflowsPlugin};
pub use knowledge_plugins::{NotebookLmPlugin, WikiPlugin, NotebooksPlugin, OrgModePlugin, MarkdownPlugin};
pub use modeling_plugins::{HaskellPlugin, MiniZincPlugin};
